packages:
  - 'web/dashboard'             # Dashboard application only
  - 'shared/*'                  # Shared JS/TS packages
  - '!web/docs'                 # Explicitly exclude docs - standalone project
  # backend/ is not included - Python handles itself