import type { Metadata } from "next";
import { ABeeZee, Roboto } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const aBeeZee = ABeeZee({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-abee-zee",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${aBeeZee.variable} `}>
      <body className={`antialiased min-h-screen`}>
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
